### ISSUE TITLE
Error "global name 'self' is not defined"

### ISSUE THREAD

**Issue by singultus** [derpicknicker1/OctoPrint-Mmu2filamentselect#12]
Hi there!

My first post on github :-). I stumbled over a problem during update while reading my OctoPi log (OctoPrint 1.3.12 running on OctoPi 0.16.0)
[octoprint.log](https://github.com/derpicknicker1/OctoPrint-Mmu2filamentselect/files/4022102/octoprint.log)
:

`2019-12-29 20:55:59,878 - octoprint.plugins.softwareupdate - ERROR - Error while retrieving update information from plugin mmu2filamentselect
Traceback (most recent call last):
File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/init.py", line 127, in _get_configured_checks
hook_checks = hook()
File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mmu2filamentselect/init.py", line 108, in get_update_information
displayName=self._plugin_name,
NameError: global name 'self' is not defined`

What's going on here? BTW, plugin seems to be working fine.
Cheers singultus

**Comment by Oberreiter** [comment]
I have the same Issue.
`2020-05-19 13:10:58,625 - octoprint.plugins.softwareupdate - ERROR - Error while retrieving update information from plugin mmu2filamentselect
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 148, in _get_configured_checks
    hook_checks = hook()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mmu2filamentselect/__init__.py", line 108, in get_update_information
    displayName=self._plugin_name,
NameError: global name 'self' is not defined`
